### ISSUE TITLE
Relatório de Avaliação de validação WebStandard - HTML e CSS

### ISSUE THREAD

**Issue by alexcyrillo** [alexcyrillo/Projeto-Front-End#10]
- HTML - https://validator.w3.org/
- CSS - https://jigsaw.w3.org/css-validator/
- LINK quebrados - https://validator.w3.org/checklink

https://stage.icurti.com/

**Comment by sica14** [comment]
HTML checker:
Warning: Evitar valores de viewport que impeçam os usuários de redimensionar documentos. Linha 9 coluna 5, até linha 12 coluna 6.
Warning2: O atributo "type" é desnecessario para o recurso do javascript. Da linha 134 coluna 5 até a linha 137 coluna 5

CSS checker: Erros enconrados:
URI : https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css Linha 6: <html>
<body>

.fa-rotate-by | var(--fa-rotate-angle, none) não é um valor transform : rotate(var(--fa-rotate-angle, none))
-- | --



</body>
</html>

URI : https://stage.icurti.com/css/stylesheet.css Linhas:
10: Erro de valor : font-family Presença de muitos valores ou valores não reconhecidos : "GT Walsheim",sans-serif
14: Lamento, a at-rule @tailwind não está implementada.
15 e 16 erros iguais a 14
18: Lamento, a at-rule @layer não está implementada.
1096:A propriedade overflow-clip-margin não existe : unset
1102: Erro de valor : color Presença de muitos valores ou valores não reconhecidos : invert(36%) sepia(90%) saturate(812%) hue-rotate(170deg) brightness(101%) contrast(97%)
1526: Erro de valor : font "Open Sans" não é um valor font : "Open Sans",sans-serif
1533: Erro de valor : font "Open Sans" não é um valor font : "Open Sans",sans-serif
1540: Erro de valor : font "Open Sans" não é um valor font : "Open Sans",sans-serif
1547: Erro de valor : font "Open Sans" não é um valor font : "Open Sans",sans-serif
1554 Erro de valor : font "Open Sans" não é um valor font : "Open Sans",sans-serif

URI : https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css
Linha 38: Erro de valor : cursor hand não é um valor cursor : hand

URI : https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
Linha 6: var(--fa-rotate-angle, none) não é um valor transform : rotate(var(--fa-rotate-angle, none))

URI : https://stage.icurti.com/css/jornada_convidado/presentes/gallery.css
Erros nas linhas 1,39 e 55

URI : https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
Linha 6: var(--fa-rotate-angle, none) não é um valor transform : rotate(var(--fa-rotate-angle, none))

URI : https://stage.icurti.com/css/jornada_convidado/presentes/gifts.css Linhas
8: Erro de valor : font-family Presença de muitos valores ou valores não reconhecidos : "GT Walsheim",sans-serif
10: Erro de parseamento };

URI : https://stage.icurti.com/assets/index-7367eb9e.css
Erro na linha 1


Link checker não apresentou erros: Checked 1 document in 47.39 seconds.
