### ISSUE TITLE
Avaliação Heurística do Icurti.com

### ISSUE THREAD

**Issue by alexcyrillo** [alexcyrillo/Projeto-Front-End#12]
Avaliar

- [ ] Landing Page Inicial 
- [ ] Criação da Lista
- [ ] Dashboard / Configuração - Lista/ Pagamentos/ Perfil

**Comment by sica14** [comment]
Landing Page: Trocar as fotos para fotos de festas aniversario, casamento, confraternizações, para fazer mais sentido com a proposta do projeto.
Dashboard/Configuração: Clicar em minha conta ou no meu nome acaba levando para o mesmo lugar, ao clicar no nome deveria abrir a opção do meu cadastro direto para poder mudar foto e nome por exemplo.
Criação da Lista: Adicionar opções nas categorias das listas em vez de ser "todas",
