### ISSUE TITLE
Elaborar o documento de visão

### ISSUE THREAD

**Issue by alexcyrillo** [alexcyrillo/Projeto-Front-End#3]
Colocar o documento de Visão no template proposto

- Definindo o cenário do problema.
- E as principais funcionalidades.

**Comment by phabdalla** [comment]
### **Introdução**
- Objetivo do site é facilitar e viabilizar com suas funcionalidades a organização de casamentos e criar um canal direto com os convidados. Juntamente com o site, há funcionalidades que prezam facilitar algumas decisões do noivo e da noiva.

### Descrição do Problema 
- Nosso projeto visa aperfeiçoar e melhorar a experiencia do usuário tornando o site mais intuitivo e de fácil entendimento de todas as ferramentas dispostas. Permitindo assim uma acessibilidade maior para novo integrantes para o iCasei.
