### ISSUE TITLE
Desenvolver o protótipo do iCurti

### ISSUE THREAD

**Issue by alexcyrillo** [alexcyrillo/Projeto-Front-End#9]
- Considerando a Análise Hierárquica de Tarefas para a decomposição de ações.
- Prototipar todas as partes do site.
- Destaque para a criação da lista.

**Comment by phabdalla** [comment]
[https://www.figma.com/design/bAuwxsn6KKE9zouqWlQZNK/Untitled?node-id=0-1&t=lrIJmjlbB3sEjUmu-1](url)
